- anat: /data/site-1/sub-001/ses-1/anat/sub-001_T1w.nii.gz
  creds_path: null
  func:
    func_run-1: /data/site-1/sub-001/ses-1/func/sub-001_task-func_run-1_bold.nii.gz
  site: site-1
  subject_id: sub-001
  unique_id: ses-1
- anat: /data/site-1/sub-002/ses-1/anat/sub-002_T1w.nii.gz
  creds_path: null
  func:
    func_run-1: /data/site-1/sub-002/ses-1/func/sub-002_task-func_run-1_bold.nii.gz
    func_run-2: /data/site-1/sub-002/ses-1/func/sub-002_task-func_run-2_bold.nii.gz
  site: site-1
  subject_id: sub-002
  unique_id: ses-1
- anat: s3://bucket_name/s3_data/site-2/sub-001/ses-1/anat/sub-001_T1w.nii.gz
  creds_path: /path/to/AWS_creds.csv
  func:
    func_run-1: /data/site-2/sub-001/ses-1/func/sub-001_task-func_run-1_bold.nii.gz
  site: site-2
  subject_id: sub-001
  unique_id: ses-1