# CPAC Data Configuration File
# Version 1.0.3
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- anat: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/Brown/sub-0026001/ses-1/anat/sub-0026001_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/Brown/sub-0026001/ses-1/func/sub-0026001_ses-1_task-rest_run-1_bold.nii.gz
    scan_parameters: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/Brown/task-rest_bold.json
  site: Brown
  subject_id: '0026001'
  unique_id: '1'