#!/usr/bin/env python3
import sys


def replace_primary_repo(yaml_string, local_owner):
    return yaml_string.replace('ghcr.io/fcp-indi',
                               f'ghcr.io/{local_owner.lower()}')


if __name__ == '__main__':
    if len(sys.argv) != 5:
        raise SyntaxError('Usage: local_ghcr $FILE $OWNER $DOCKER_TAG $SHA')
    file, owner, tag, sha = sys.argv[1:]
    dockerfiles = '.github/Dockerfiles'
    new_Dockerfile = replace_primary_repo(
        open(file, 'r').read(),
        owner.lower()
    )
    if '-lite-' in file:
        tag = tag.lower().split("c-pac:")[1][:-5]
        if tag != 'latest-lite':
            new_Dockerfile = new_Dockerfile.replace(':latest-bionic',
                                                    f':{tag}')
        new_Dockerfile = new_Dockerfile.replace(f':{tag}', f':{tag}-{sha}')
    open(file, 'w').write(new_Dockerfile)
