#!/usr/bin/env python3
import re
import sys


def replace_primary_repo(yaml_string, local_owner):
    return yaml_string.replace('ghcr.io/fcp-indi',
                               f'ghcr.io/{local_owner.lower()}')


if __name__ == '__main__':
    if len(sys.argv) != 5:
        raise SyntaxError('Usage: local_ghcr $FILE $OWNER $SHA')
    file, owner, sha = sys.argv[1:]
    dockerfiles = '.github/Dockerfiles'
    new_Dockerfile = replace_primary_repo(
        open(file, 'r').read(),
        owner.lower()
    )
    pattern = (r'ghcr\.io\/fcp-indi\/c-pac\/(?:[A-Za-z0-9\-_\.]+):'
               r'([A-Za-z0-9\-_\.]+)').replace('fcp-indi', owner.lower())
    new_Dockerfile = re.sub(pattern, sha, new_Dockerfile)
    open(file, 'w').write(new_Dockerfile)
