name: Build C-PAC image

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string

jobs:
  C-PAC:
    name: Build Docker C-PAC images
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v6
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          overprovision-lvm: 'true'
      - name: Check out C-PAC
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Dockerfile
        if: github.ref_type == 'branch'
        run: |
          if [[ "${{ inputs.variant }}" == "" ]]
          then
            OS=jammy
          else
            VARIANT=-${{ inputs.variant }}
            if [[ "${{ inputs.variant }}" == "fMRIPrep-LTS" ]]
            then
              OS=xenial
            elif [[ "${{ inputs.variant }}" == "ABCD-HCP" ]]
            then
              OS=bionic
            else
              OS=jammy
            fi
          fi
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          if [[ ! $GITHUB_BRANCH == 'main' ]] && [[ ! $GITHUB_BRANCH == 'develop' ]]
          then
            DOCKERFILE=.github/Dockerfiles/C-PAC.develop$VARIANT-$OS.Dockerfile
          elif [[ $GITHUB_BRANCH == 'develop' ]]
          then
            DOCKERFILE=.github/Dockerfiles/C-PAC.develop$VARIANT-$OS.Dockerfile
          elif [[ $GITHUB_BRANCH == 'main' ]]
          then
            if [[ $VARIANT == "" ]]
            then
              DOCKERFILE=Dockerfile
            else
              DOCKERFILE=variant$VARIANT.Dockerfile
            fi
          fi
          echo DOCKERFILE="${DOCKERFILE}" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Set Dockerfile
        if: github.ref_type == 'tag'
        run: |
          if [[ "${{ inputs.variant }}" != "" ]]
          then
            VARIANT=-${{ inputs.variant }}
          fi
          if [[ $VARIANT == "" ]]
          then
            DOCKERFILE=Dockerfile
          else
            DOCKERFILE=variant$VARIANT.Dockerfile
          fi
          echo DOCKERFILE="${DOCKERFILE}" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Prep Dockerfiles for forked repository
        if: ${{ github.repository_owner }} != 'FCP-INDI'
        run: .github/scripts/local_ghcr $DOCKERFILE ${{ github.repository_owner }} ${{ github.sha }}
      - name: See Dockerfile
        run: |
          echo $DOCKERFILE
          cat $DOCKERFILE
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          flavor:
            suffix=-${{ github.sha }}
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,priority=800
            type=ref,event=pr,priority=799
            type=raw,value=latest,enable={{is_default_branch}},priorty=700
            type=sha,priority=600,onlatest=false
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max,compression=zstd
          context: .
          file: ${{ env.DOCKERFILE }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          push: true
          sbom: false
          tags: ${{ steps.meta.outputs.tags }}
