name: Gather schema for GUI

on:
  push:
    branches:
      - develop
      - js/schema

jobs:
  gather:
    name: Gather schema
    runs-on: ubuntu-latest
    container: 
      image: fcpindi/c-pac:nightly
    steps:
      - name: Make JSON schema
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}_GUI.git
          cd ${GITHUB_REPOSITORY}_GUI
          python /code/.github/scripts/gui/gather_schema.py $PWD/c-pac/resources/pipeline/schema.json
          cat $PWD/c-pac/resources/pipeline/schema.json
          