name: Gather schema for GUI

on:
  push:
    branches:
      - develop
      - js/schema

jobs:
  gather:
    name: Gather schema
    runs-on: ubuntu-latest
    container: 
      image: fcpindi/c-pac:nightly
    steps:
      - name: Checkout C-PAC
        uses: actions/checkout@v2
        with:
          path: C-PAC
      - name: Checkout GUI
        uses: actions/checkout@v2
        with:
          repository: FCP-INDI/C-PAC_GUI
          path: C-PAC_GUI
      - name: Make JSON schema
        run: |
          mkdir -p C-PAC_GUI/c-pac/resources/pipeline
          python C-PAC/.github/scripts/gui/gather_schema.py C-PAC_GUI/c-pac/resources/pipeline/schema.json
          cat C-PAC_GUI/c-pac/resources/pipeline/schema.json
